homeassistant: !include config/homeassistant.yaml
frontend:
http:
  api_password: !secret http_password
updater:
discovery:
conversation:
history:
logbook:
sun:

automation: !include_dir_merge_list config/automations/
binary_sensor: !include config/binary_sensors.yaml
group: !include_dir_merge_named config/groups/
sensor: !include config/sensors.yaml
switch: !include config/switches/switches.yaml
zwave: !include config/zwave.yaml
shell_command: !include_dir_merge_named config/shell_commands/
media_player: !include config/media_players.yaml
notify: !include config/notifications.yaml
script: !include_dir_merge_named config/scripts/
scene: !include_dir_merge_list config/scenes/
input_select: !include config/input_selects.yaml
mqtt: !include config/mqtt.yaml
device_tracker: !include config/device_tracker.yaml
cover: !include config/covers.yaml
calendar:
  google:
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret
    track_new_calendar: False

#input_slider: !include config/input_sliders.yaml
zone 1: !include config/zones/home.yaml
zone 2: !include config/zones/work.yaml
