open_netflix:
  alias: Open Netflix
  sequence:
    - alias: Turn on TV
      service_template: >-
        {%- if states['switch']['living_room_tv'].state == 'on' %}
          shell_command.irsend_tv_exit
        {% else %}
          switch.turn_on
        {% endif -%}

      entity_id: switch.living_room_tv
    - alias: TV online
      wait_template: "{{ states['switch']['living_room_tv'].state == 'on' }}"
    - alias: Delay
      delay:
        milliseconds: 5
    - alias: Press exit
      service: shell_command.irsend_tv_key_exit
    - alias: Delay
      delay:
        milliseconds: 5
    - alias: Press smart hub
      service: shell_command.irsend_tv_smart_hub
    - alias: Delay
      delay:
        seconds: 3
    - alias: Press left
      service: shell_command.irsend_tv_key_left
    - alias: Delay
      delay:
        milliseconds: 5
    - alias: Press enter
      service: shell_command.irsend_tv_key_select
    - alias: Delay
      delay:
        seconds: 3
    - alias: Press enter
      service: shell_command.irsend_tv_key_select
    - alias: Delay
      delay:
        seconds: 4
    - alias: Press right
      service: shell_command.irsend_tv_key_right
    - alias: Delay
      delay:
        milliseconds: 5
    - alias: Press enter
      service: shell_command.irsend_tv_key_select
