open_netflix:
  alias: Open Netflix
  sequence:
    - alias: Turn on TV
      service_template: >-
        {%- if states['switch']['living_room_tv'].state == 'on' %}
          shell_command.irsend_tv_smart_hub
        {% else %}
          switch.turn_on
        {% endif -%}

      entity_id: switch.living_room_tv
    - alias: Delay
      delay: 00:00:09
    - alias: Press left
      service: shell_command.irsend_tv_key_left
    - alias: Delay
      delay: 00:00:01
    - alias: Press enter
      service: shell_command.irsend_tv_key_select
    - alias: Delay
      delay: 00:00:03
    - alias: Press enter
      service: shell_command.irsend_tv_key_select
    - alias: Delay
      delay: 00:00:04
    - alias: Press right
      service: shell_command.irsend_tv_key_right
    - alias: Delay
      delay: 00:00:01
    - alias: Press enter
      service: shell_command.irsend_tv_key_select
