reboot:
  alias: Server (reboot)
  sequence:
    - alias: Server (reboot)
      service: shell_command.reboot_server
hass_restart:
  alias: Home Assistant (restart)
  sequence:
    - alias: Git pull
      service: shell_command.hass_git_pull
    - alias: Restart Home Assistant
      service: homeassistant.restart
nicholas_leaving:
  alias: Nicholas Leaving
  sequence:
    - alias: Nicholas mobile phone only
      service: scene.nicholas_mobile_phone_only
