reboot:
  alias: Server (reboot)
  sequence:
    - alias: Server (reboot)
      service: shell_command.reboot_server
hass_restart:
  alias: Home Assistant (restart)
  sequence:
    - alias: Git pull
      service: shell_command.hass_git_pull
    - alias: Restart Home Assistant
      service: homeassistant.restart
nicholas_leaving:
  alias: Nicholas Leaving
  sequence:
    - alias: Nicholas mobile phone only
      service: scene.nicholas_mobile_phone_only
away:
  alias: Away
  sequence:
    - alias: Away scene
      service: scene.turn_on
      entity_id: scene.away
    - service: scene.turn_on
      entity_id: scene.nicholas_mobile_phone_only
    - condition: state
      entity_id: switch.living_room_tv
      state: 'on'
    - alias: Turn off TV
      service: switch.turn_off
      entity_id: switch.living_room_tv
plex_show:
  alias: Plex Show
  sequence:
    - alias: Plex Show
      service: shell_command.plex_show
google_test:
  alias: Google Test
  sequence:
    - alias: Testing Google Home
      service: tts.google_say
      data:
        message: 'May the Force be with you.'