toggle_lights:
  alias: Toggle Lights
  sequence:
    - service: light.toggle
      entity_id: light.livingroomlights_level_2_0
    - delay:
        seconds: 7
    - service: light.toggle
      entity_id: light.livingroomlights_level_2_0
