toggle_lights:
  alias: Toggle Lights
  sequence:
    - service: light.toggle
      entity_id: light.livingroomlights_level_2_0
    - delay:
        seconds: 7
    - service_template: "light.turn_{{ states('light.livingroomlights_level_2_0') }}"
      entity_id: light.livingroomlights_level_2_0
