toggle_lights:
  alias: Toggle Lights
  sequence:
    - service: light.toggle
      data:
        entity_id: light.livingroomlights_level_2_0
    - delay:
        seconds: 3
    - service: script.turn_on
      data:
        entity_id: script.toggle_lights_again
toggle_lights_again:
  alias: Toggle Lights Again
  sequence:
    - service: light.toggle
      data:
        entity_id: light.livingroomlights_level_2_0