toggle_lights:
  alias: Toggle Lights
  sequence:
    - service: automation.toggle
      data:
        entity_id: automation.girls_bedtime_reverse
    - delay:
        seconds: 3
    - service: light.toggle
      data:
        entity_id: light.livingroomlights_level_2_0
