- name: Livingroom normal
  entities:
    light.livingroomlights_level:
      state: on
      brightness: 255
- name: Livingroom dim
  entities:
    light.livingroomlights_level:
      state: on
      brightness: 75
- name: Livingroom dark
  entities:
    light.livingroomlights_level:
      state: off
- name: Away
  entities:
    light.livingroomlights_level:
      state: off
    cover.garage_door:
      state: closed
- name: Nicholas Mobile Phone Only
  entities:
    switch.home_phone_nicholas:
      state: off
    switch.mobile_phone_nicholas:
      state: on
    switch.work_phone_nicholas:
      state: off
