#- name: Theater Mode Disabled
#  entities:
#    group.theater_automations:
#      state: off
#- name: Theater Mode Always On
#  entities:
#    group.theater_automations:
#      state: on
#- name: Theater Mode After Sunset TVShow
#  entities:
#    group.theater_automations:
#      state: on
- name: Theater Mode After Sunset Hybrid TVShow
  entities:
    scene.livingroom_dim:
      state: on
- name: Theater Mode After Sunset Hybrid Movie
  entities:
    scene.livingroom_dark:
      state: on
- name: Theater Mode Always On Dim Everything TVShow
  entities:
    scene.livingroom_dim:
      state: on
- name: Theater Mode Always On Dim Everything Movie
  entities:
    scene.livingroom_dim:
      state: on
- name: Theater Mode After Sunset Lights Out TVShow
  entities:
    scene.livingroom_dark:
      state: on
- name: Theater Mode After Sunset Lights Out Movie
  entities:
    scene.livingroom_dark:
      state: on
#- name: Theater Style Hybrid
#- name: Theater Style Dim Everything
#- name: Theater Style Lights Out