- name: Theater Mode After Sunset Hybrid TVShow
  entities:
    scene.livingroom_dim:
      state: on
- name: Theater Mode After Sunset Hybrid Movie
  entities:
    scene.livingroom_dark:
      state: on
- name: Theater Mode After Sunset Dim Everything TVShow
  entities:
    scene.livingroom_dim:
      state: on
- name: Theater Mode After Sunset Dim Everything Movie
  entities:
    scene.livingroom_dim:
      state: on
- name: Theater Mode After Sunset Lights Out TVShow
  entities:
    scene.livingroom_dark:
      state: on
- name: Theater Mode After Sunset Lights Out Movie
  entities:
    scene.livingroom_dark:
      state: on
- name: Theater Mode Always On Hybrid TVShow
  entities:
    scene.livingroom_dim:
      state: on
- name: Theater Mode Always On Hybrid Movie
  entities:
    scene.livingroom_dark:
      state: on
- name: Theater Mode Always On Dim Everything TVShow
  entities:
    scene.livingroom_dim:
      state: on
- name: Theater Mode Always On Dim Everything Movie
  entities:
    scene.livingroom_dim:
      state: on
- name: Theater Mode Always On Lights Out TVShow
  entities:
    scene.livingroom_dark:
      state: on
- name: Theater Mode Always On Lights Out Movie
  entities:
    scene.livingroom_dark:
      state: on
- name: Theater Mode Disabled Hybrid TVShow
- name: Theater Mode Disabled Hybrid Movie
- name: Theater Mode Disabled Dim Everything TVShow
- name: Theater Mode Disabled Dim Everything Movie
- name: Theater Mode Disabled Lights Out TVShow
- name: Theater Mode Disabled Lights Out Movie
