- alias: "Nicholas comes home"
  trigger:
    platform: state
    entity_id: device_tracker.plex_na
    to: 'home'
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_normal
    - service: switch.turn_on
      entity_id: switch.gv_nicholas_home
    - service: switch.turn_off
      entity_id: switch.gv_nicholas_work
    - service: switch.turn_off
      entity_id: switch.gv_nicholas_mobile
- alias: "Nicholas leaves home"
  trigger:
    platform: state
    entity_id: device_tracker.plex_na
    from: 'home'
    to: 'not_home'
  action:
    - service: switch.turn_off
      entity_id: switch.gv_nicholas_home
    - service: switch.turn_off
      entity_id: switch.gv_nicholas_work
    - service: switch.turn_on
      entity_id: switch.gv_nicholas_mobile
- alias: "Nicholas arrives at work"
  trigger:
    platform: state
    entity_id: device_tracker.plex_na
    to: 'work'
  action:
    - service: switch.turn_off
      entity_id: switch.gv_nicholas_home
    - service: switch.turn_on
      entity_id: switch.gv_nicholas_work
    - service: switch.turn_off
      entity_id: switch.gv_nicholas_mobile
- alias: "Nicholas leaves work"
  trigger:
    platform: state
    entity_id: device_tracker.plex_na
    from: 'work'
    to: 'not_home'
  action:
    - service: switch.turn_off
      entity_id: switch.gv_nicholas_home
    - service: switch.turn_on
      entity_id: switch.gv_nicholas_work
    - service: switch.turn_off
      entity_id: switch.gv_nicholas_mobile