- alias: "Turn Front Porch Lights On"
  trigger:
    platform: event
    event_type: state_changed
    event_data:
      entity_id: sun.sun
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -3.30
      - condition: state
        entity_id: switch.frontporchlight_switch
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.frontporchlight_switch
#    - service: switch.turn_off
#      entity_id: switch.outsideoutlet_switch
- alias: "Turn Front Porch Lights Off"
  trigger:
    platform: event
    event_type: state_changed
    event_data:
      entity_id: sun.sun
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        above: -3.31
      - condition: state
        entity_id: switch.frontporchlight_switch
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.frontporchlight_switch
#    - service: switch.turn_on
#      entity_id: switch.outsideoutlet_switch
- alias: "Ensure Front Porch Lights Stay On"
  trigger:
    - platform: state
      entity_id: switch.frontporchlight_switch
      state: 'off'
      for:
        seconds: 30
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -3.30 # exclusive; below = -2.51, -2.52, -2.53, etc
  action:
    - service: switch.turn_on
      entity_id: switch.frontporchlight_switch
- alias: "Ensure Front Porch Lights Stay Off"
  trigger:
    - platform: state
      entity_id: switch.frontporchlight_switch
      state: 'on'
      for:
        seconds: 30
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: -3.31 # exclusive; above = -2.50, -2.49, -2.48, etc
  action:
    - service: switch.turn_off
      entity_id: switch.frontporchlight_switch
