- alias: "Christmas Tree On"
  trigger:
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: sun.sun
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: light.livingroomlights_level_2_0
  condition:
    # TURN ON         DURING CHRISTMAS              and either       AT NIGHT WHILST LIGHTS ARE OFF        or   ANYTIME LIVING LIGHTS ARE ON
    # if ( (holiday && holiday_name == 'Christmas') && ((sun.elevation <= -3.30 && living_lights == 'off') || living_lights == 'on') )
    - condition: and
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: calendar.holiday_lighting
              state: 'on'
            - condition: template
              value_template: "{{ states.calendar.holiday_lighting.attributes.message == 'Christmas' }}"
        - condition: or
          conditions:
            - condition: and
              conditions:
                - condition: numeric_state
                  entity_id: sun.sun
                  value_template: '{{ state.attributes.elevation }}'
                  below: -3.30
                - condition: state
                  entity_id: light.livingroomlights_level_2_0
                  state: 'off'
            - condition: state
              entity_id: light.livingroomlights_level_2_0
              state: 'on'
  action:
    - service_template: switch.turn_on
      data:
        entity_id: switch.diningoutlet_switch_4_0
- alias: "Christmas Tree Off"
  trigger:
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: sun.sun
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: light.livingroomlights_level_2_0
  condition:
    # TURN OFF      DURING CHRISTMAS              and        DURING DAY WHILST LIGHTS ARE OFF
    # if ( holiday && holiday_name == 'Christmas' && sun.elevation >= -3.31 && living_lights == 'off')
    - condition: and
      conditions:
        - condition: state
          entity_id: calendar.holiday_lighting
          state: 'on'
        - condition: template
          value_template: "{{ states.calendar.holiday_lighting.attributes.message == 'Christmas' }}"
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          above: -3.31
        - condition: state
          entity_id: light.livingroomlights_level_2_0
          state: 'off'
  action:
    - service_template: switch.turn_off
      data:
        entity_id: switch.diningoutlet_switch_4_0
