- alias: "Holiday lighting On"
  trigger:
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: sun.sun
  condition:
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          below: -2.50
        - condition: state
          entity_id: calendar.holiday_lighting
          state: 'on'
        - condition: template
          value_template: "{{ states.calendar.holiday_lighting.attributes.message|length > 0 }}"
        - condition: state
          entity_id: input_boolean.holiday_lighting
          state: 'off'
  action:
    - service: notify.html5
      data:
        message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M %p') }}: Turned on the {{ states.calendar.holiday_lighting.attributes.message }} lights. {{ states.calendar.holiday_lighting.attributes.description }}"
        title: "{{ states.calendar.holiday_lighting.attributes.message }} Lights"
        data:
          tag: "holiday_lighting"
    - service_template: scene.turn_on
      data_template:
        entity_id: "scene.holiday_lighting_{{ states.calendar.holiday_lighting.attributes.message|lower|replace(' ', '_')|replace('.', '')|replace(',', '')|replace(\"'\", '') }}_on"
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.holiday_lighting
- alias: "Holiday lighting Off"
  trigger:
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: sun.sun
  condition:
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          above: -2.51
        - condition: state
          entity_id: calendar.holiday_lighting
          state: 'on'
        - condition: template
          value_template: "{{ states.calendar.holiday_lighting.attributes.message|length > 0 }}"
        - condition: state
          entity_id: input_boolean.holiday_lighting
          state: 'on'
  action:
    - service: notify.html5
      data:
        message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M %p') }}: Turned off the {{ states.calendar.holiday_lighting.attributes.message }} lights. {{ states.calendar.holiday_lighting.attributes.description }}"
        title: "{{ states.calendar.holiday_lighting.attributes.message }} Lights"
        data:
          tag: "holiday_lighting"
    - service_template: scene.turn_on
      data_template:
        entity_id: "scene.holiday_lighting_{{ states.calendar.holiday_lighting.attributes.message|lower|replace(' ', '_')|replace('.', '')|replace(',', '')|replace(\"'\", '') }}_off"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.holiday_lighting
- alias: "Non-Holiday lighting"
  trigger:
    - platform: state
      entity_id: calendar.holiday_lighting
      to: 'off'
  action:
    - service: notify.html5
      data:
        message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M %p') }}: All lights and switches are now set to their normal states."
        title: "Holiday over"
        data:
          tag: "holiday_lighting"
    - service_template: scene.turn_on
      data_template:
        entity_id: "scene.non_holiday_lighting"
