- alias: "mqtt"
  trigger:
    - platform: state
      entity_id: sensor.plexpy_body
  action:
    - service: notify.html5
      data_template:
        message: "{{ states('sensor.plexpy_body') }}"
        title: "{{ states('sensor.plexpy_title') }}"
        data:
          tag: "{{ states('sensor.plexpy_tag') }}"
          icon: "{{ states('sensor.plexpy_poster')|replace('http://', 'https://') }}"