- alias: "Girl's Bedtime"
  trigger:
    - platform: time
      hours: 20
      minutes: 00
      seconds: 00
    - platform: time
      hours: 20
      minutes: 20
      seconds: 00
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: light.livingroomlights_level_2_0
          state: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: "scene.livingroom_dim"
- alias: "Reset Girl's Bedtime"
  trigger:
    - platform: time
      hours: 20
      minutes: 00
      seconds: 30
    - platform: time
      hours: 20
      minutes: 20
      seconds: 30
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ states.light.livingroomlights_level_2_0.attributes.brightness == 75 }}"
  action:
    - service: scene.turn_on
      data_template:
        entity_id: "scene.livingroom_normal"
