- alias: "Girl's Bedtime"
  trigger:
    - platform: time
      hours: 20
      minutes: 00
      seconds: 00
    - platform: time
      hours: 20
      minutes: 00
      seconds: 15
    - platform: time
      hours: 20
      minutes: 20
      seconds: 00
    - platform: time
      hours: 20
      minutes: 20
      seconds: 15
    - platform: time
      hours: 00
      minutes: 58
      seconds: 00
    - platform: time
      hours: 00
      minutes: 58
      seconds: 15
  action:
    - service: light.toggle
      entity_id: light.livingroomlights_level_2_0
