- alias: "Girl's Bedtime"
  trigger:
    - platform: time
      hours: 20
      minutes: 00
      seconds: 00
    - platform: time
      hours: 20
      minutes: 30
      seconds: 00
  action:
    - service:
        service: homeassistant.turn_on
        variables:
          light_state: "{{ states(light.livingroomlights_level_2_0) }}"
      entity_id: script.toggle_lights
