- alias: "Girl's Bedtime"
  trigger:
    - platform: time
      hours: 20
      minutes: 0
      seconds: 0
    - platform: time
      hours: 20
      minutes: 0
      seconds: 15
    - platform: time
      hours: 20
      minutes: 20
      seconds: 0
    - platform: time
      hours: 20
      minutes: 20
      seconds: 15
    - platform: time
      seconds: 0
    - platform: time
      seconds: 20
  action:
    - service: light.toggle
      entity_id: light.livingroomlights_level_2_0
