- alias: "Girl's Bedtime"
  trigger:
    - platform: time
      hours: 20
      minutes: 00
      seconds: 00
    - platform: time
      hours: 20
      minutes: 00
      seconds: 15
    - platform: time
      hours: 20
      minutes: 20
      seconds: 00
    - platform: time
      hours: 20
      minutes: 20
      seconds: 15
#    - platform: time
#      seconds: 00
  action:
    - service_template: "input_boolean.turn_{{ states('light.livingroomlights_level_2_0') }}"
      entity_id: input_boolean.girls_bedtime_living_lights
    - service: light.toggle
      entity_id: light.livingroomlights_level_2_0
    - service_template: "light.turn_{{ states('input_boolean.girls_bedtime_living_lights') }}"
      entity_id: light.livingroomlights_level_2_0