- alias: "Girl's Bedtime"
  trigger:
    - platform: time
      hours: 19
      minutes: 52
      seconds: 0
    - platform: state
      entity_id: light.livingroomlights_level_2_0
  action:
    - service: notify.html5
      data:
        message: "trigger.from_state.state={{ trigger.from_state.state }}; trigger.from_state.attributes.brightness={{ trigger.from_state.attributes.brightness }}; "
        title: "Plex {{ states('media_player.tv_un55h6300') }} {{ states.media_player.tv_un55h6300.attributes.media_content_type }}"
        data:
          tag: "debug"