- alias: "Girl's Bedtime"
  trigger:
    - platform: time
      hours: 20
      minutes: 00
      seconds: 00
    - platform: time
      hours: 20
      minutes: 00
      seconds: 10
    - platform: time
      hours: 20
      minutes: 30
      seconds: 00
    - platform: time
      hours: 20
      minutes: 30
      seconds: 10
  action:
    - service: light.toggle
      entity_id: light.livingroomlights_level_2_0
