- alias: "Girl's Bedtime"
  trigger:
    - platform: time
      hours: 20
      minutes: 00
      seconds: 00
    - platform: time
      hours: 20
      minutes: 30
      seconds: 00
  action:
    - service: script.turn_on
      entity_id: script.toggle_lights
