#- alias: "Plex Media Server Stopped"
#  trigger:
#    platform: state
#    entity_id: switch.plexmediaserver
#    to: 'off'
#  action:
#    - service: notify.pushbullet
#      data:
#        message: "The Plex Media Server has stopped! Please check it's status and/or restart it."
#        title: "Home Assistant: Plex Media Server"
#- alias: "Headphones Stopped"
#  trigger:
#    platform: state
#    entity_id: switch.headphones
#    to: 'off'
#  action:
#    - service: notify.pushbullet
#      data:
#        message: "The Headphones daemon has stopped! Please check it's status and/or restart it."
#        title: "Home Assistant: Headphones"
#- alias: "Sonarr Stopped"
#  trigger:
#    platform: state
#    entity_id: switch.sonarr
#    to: 'off'
#  action:
#    - service: notify.pushbullet
#      data:
#        message: "The Sonarr daemon has stopped! Please check it's status and/or restart it."
#        title: "Home Assistant: Sonarr"
#- alias: "Couch Potato Stopped"
#  trigger:
#    platform: state
#    entity_id: switch.couch_potato
#    to: 'off'
#  action:
#    - service: notify.pushbullet
#      data:
#        message: "The Couch Potato daemon has stopped! Please check it's status and/or restart it."
#        title: "Home Assistant: Couch Potato"
##    - service: switch.turn_on
##      entity_id: switch.couch_potato
#- alias: "Deluge Daemon Stopped"
#  trigger:
#    platform: state
#    entity_id: switch.deluged
#    to: 'off'
#  action:
#    - service: notify.pushbullet
#      data:
#        message: "The Deluge daemon has stopped! Please check it's status and/or restart it."
#        title: "Home Assistant: Deluge"
#- alias: "Deluge Web Stopped"
#  trigger:
#    platform: state
#    entity_id: switch.delugeweb
#    to: 'off'
#  action:
#    - service: notify.pushbullet
#      data:
#        message: "The Deluge Web daemon has stopped! Please check it's status and/or restart it."
#        title: "Home Assistant: Deluge Web"
#- alias: "Jackett Stopped"
#  trigger:
#    platform: state
#    entity_id: switch.jackett
#    to: 'off'
#  action:
#    - service: notify.pushbullet
#      data:
#        message: "The Jackett daemon has stopped! Please check it's status and/or restart it."
#        title: "Home Assistant: Jackett"
