- alias: "Plex Media Server Stopped"
  trigger:
    platform: state
    entity_id: switch.plexmediaserver
    to: 'off'
  action:
    - service: notify.html5
      data:
        message: "{{ states('sensor.now') }}: The Plex Media Server has stopped! Please check it's status and/or restart it."
        title: "Home Assistant: Plex Media Server"
        target: ["alipaz_y50", "heremedia_laptop"]
- alias: "Headphones Stopped"
  trigger:
    platform: state
    entity_id: switch.headphones
    to: 'off'
  action:
    - service: notify.html5
      data:
        message: "{{ states('sensor.now') }}: The Headphones daemon has stopped! Please check it's status and/or restart it."
        title: "Home Assistant: Headphones"
        target: ["alipaz_y50", "heremedia_laptop"]
- alias: "Sonarr Stopped"
  trigger:
    platform: state
    entity_id: switch.sonarr
    to: 'off'
  action:
    - service: notify.html5
      data:
        message: "{{ states('sensor.now') }}: The Sonarr daemon has stopped! Please check it's status and/or restart it."
        title: "Home Assistant: Sonarr"
        target: ["alipaz_y50", "heremedia_laptop"]
- alias: "Couch Potato Stopped"
  trigger:
    platform: state
    entity_id: switch.couch_potato
    to: 'off'
  action:
    - service: notify.html5
      data:
        message: "{{ states('sensor.now') }}: The Couch Potato daemon has stopped! Please check it's status and/or restart it."
        title: "Home Assistant: Couch Potato"
        target: ["alipaz_y50", "heremedia_laptop"]
#    - service: switch.turn_on
#      entity_id: switch.couch_potato
- alias: "Deluge Daemon Stopped"
  trigger:
    platform: state
    entity_id: switch.deluged
    to: 'off'
  action:
    - service: notify.html5
      data:
        message: "{{ states('sensor.now') }}: The Deluge daemon has stopped! Please check it's status and/or restart it."
        title: "Home Assistant: Deluge"
        target: ["alipaz_y50", "heremedia_laptop"]
- alias: "Deluge Web Stopped"
  trigger:
    platform: state
    entity_id: switch.deluge_web
    to: 'off'
  action:
    - service: notify.html5
      data:
        message: "{{ states('sensor.now') }}: The Deluge Web daemon has stopped! Please check it's status and/or restart it."
        title: "Home Assistant: Deluge Web"
        target: ["alipaz_y50", "heremedia_laptop"]
- alias: "Jackett Stopped"
  trigger:
    platform: state
    entity_id: switch.jackett
    to: 'off'
  action:
    - service: notify.html5
      data:
        message: "{{ states('sensor.now') }}: The Jackett daemon has stopped! Please check it's status and/or restart it."
        title: "Home Assistant: Jackett"
        target: ["alipaz_y50", "heremedia_laptop"]
