- alias: Living room tv playing
  trigger:
    - platform: state
      entity_id: media_player.tv_un55h6300
      to: 'playing'
  condition:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: sun.sun
              state: 'below_horizon'
            - condition: state
              entity_id: input_select.theater_mode
              state: 'After Sunset'
        - condition: state
          entity_id: input_select.theater_mode
          state: 'Always On'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: "scene.theater_mode_{{ states('input_select.theater_mode')|lower|replace(' ', '_') }}_{{ states('input_select.theater_style')|lower|replace(' ', '_') }}_{{ states.media_player.tv_un55h6300.attributes.media_content_type }}"
- alias: Living room tv paused/stopped
  trigger:
    - platform: state
      entity_id: media_player.tv_un55h6300
      from: 'playing'
  condition:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: input_select.theater_mode
              state: 'After Sunset'
            - condition: state
              entity_id: sun.sun
              state: 'below_horizon'
        - condition: state
          entity_id: input_select.theater_mode
          state: 'Always On'
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_normal
