light.livingroomlights_level:
  friendly_name: "Living Room Lights"
switch.frontporchlight_switch:
  friendly_name: "Front Porch Light"

media_player.rasplex:
  friendly_name: "Plex (Blue Room)"
media_player.tv_un55h6300:
  friendly_name: "Living Room TV"

device_tracker.plex_na:
  friendly_name: "Nicholas"

zone.daycare:
  friendly_name: !secret daycare_name
zone.elementary_school:
  friendly_name: !secret elementary_school_name
zone.home:
  friendly_name: Home
zone.home2:
  friendly_name: !secret home2_name
zone.sports_center:
  friendly_name: !secret sports_center_name
zone.preschool:
  friendly_name: !secret preschool_name
zone.work:
  friendly_name: Work