switch.living_room_tv:
  google_assistant: True
  google_assistant_name: TV
  aliases:
    - Living Room TV
    - Television

script.irsend_tv_key_mute:
  google_assistant: True
  google_assistant_name: Mute
  aliases:
    - Mute
    - Press Mute
    - Mute the TV
    - Mute the Living Room TV
    - Unmute
    - Press Unmute
    - Unmute the TV
    - Unmute the Living Room TV

script.irsend_tv_key_stop:
  google_assistant: True
  google_assistant_name: Stop
  aliases:
    - Stop
    - Press Stop
    - Stop the Movie
    - Stop the TV Show
    - Stop the TV

script.irsend_tv_key_pause:
  google_assistant: True
  google_assistant_name: Pause
  aliases:
    - Pause
    - Press Pause
    - Pause the Movie
    - Pause the TV Show
    - Pause the TV

script.irsend_tv_key_play:
  google_assistant: True
  google_assistant_name: Resume
  aliases:
    - Play
    - Press play
    - Play the Movie
    - Play the TV Show
    - Resume
    - Press resume
    - Resume the Movie
    - Resume the TV Show
    - Resume the TV

script.open_plex:
  google_assistant: True
  google_assistant_name: Open Plex
  aliases:
    - Open Plex
    - Open Flex
    - Open up Plex
    - Open up Flex
    - Start up Plex
    - Start up Flex
    - Start Plex
    - Start Flex
    - Turn on Plex
    - Turn on Flex
    - Let's watch something on Plex
    - Let's watch something on Flex
    - Let's watch Plex
    - Let's watch Flex
