switch.living_room_tv:
  google_assistant: True
  google_assistant_name: TV
  aliases:
    - Living Room TV
    - Television

script.irsend_tv_key_mute:
  google_assistant: True
  google_assistant_name: Mute

script.irsend_tv_key_stop:
  google_assistant: True
  google_assistant_name: Stop

script.irsend_tv_key_play:
  google_assistant: True
  google_assistant_name: Play

script.irsend_tv_key_pause:
  google_assistant: True
  google_assistant_name: Pause

script.irsend_tv_key_select:
  google_assistant: True
  google_assistant_name: Enter

script.irsend_tv_key_left:
  google_assistant: True
  google_assistant_name: Left

script.irsend_tv_key_right:
  google_assistant: True
  google_assistant_name: Right

script.irsend_tv_key_down:
  google_assistant: True
  google_assistant_name: Down

script.irsend_tv_key_up:
  google_assistant: True
  google_assistant_name: Up

script.next_episode:
  google_assistant: True
  google_assistant_name: Next Episode

script.open_plex:
  google_assistant: True
  google_assistant_name: Open Plex
  aliases:
    - Open Plex
    - Open Flex
    - Open up Plex
    - Open up Flex
    - Start up Plex
    - Start up Flex
    - Start Plex
    - Start Flex
    - Turn on Plex
    - Turn on Flex
    - Let's watch something on Plex
    - Let's watch something on Flex
    - Let's watch Plex
    - Let's watch Flex

script.open_netflix:
  google_assistant: True
  google_assistant_name: Open Netflix
  aliases:
    - Open Netflix
    - Open up Netflix
    - Start up Netflix
    - Start Netflix
    - Turn on Netflix
    - Let's watch something on Netflix
    - Let's watch Netflix
