light.livingroomlights_level:
  google_assistant: True
  google_assistant_name: Living Room Lights

cover.garage_door:
  google_assistant: True
  google_assistant_name: Garage
  aliases:
    - Garage Door

switch.diningoutlet_switch:
  google_assistant: True
  google_assistant_name: Dining Outlet
  aliases:
    - Dining Room Outlet
    - Dining Room Outlet Switch
    - Christmas Tree

scene.bedtime:
  google_assistant: True
  google_assistant_name: Go to bed
  aliases:
    - Go to bed scene
    - Go to sleep
    - Bedtime
    - Bedtime scene

script.reboot:
  google_assistant: True
  google_assistant_name: Reboot the Media Server
  aliases:
    - Reboot the Home Server
    - Restart the Media Server
    - Restart the Home Server
