automation.automation_0:
  hidden: true
automation.automation_1:
  hidden: true
automation.automation_2:
  hidden: true
automation.automation_3:
  hidden: true
automation.automation_4:
  hidden: true
automation.automation_5:
  hidden: true
automation.automation_6:
  hidden: true
