custom_ui_state_card: state-card-tiles
config:
  columns: 4
  column_width: 75px
  row_height: 55px
  gap: 3px
  color: '#DDDDDD'
  font_color: white
  entities:
    - entity: script.irsend_tv_key_a
      label: A
      background_color: red
      row: 1
    - entity: script.irsend_tv_key_b
      label: B
      background_color: green
      row: 1
    - entity: script.irsend_tv_key_c
      label: C
      background_color: yellow
      row: 1
    - entity: script.irsend_tv_key_d
      label: D
      background_color: blue
      row: 1
