custom_ui_state_card: state-card-tiles
config:
  columns: 3
  column_width: 75px
  row_height: 75px
  gap: 4px
  color: '#DDDDDD'
  font_color: '#000000'
  entities:
    - entity: script.irsend_tv_key_power
      icon: mdi:power
      label: TV
      background_color: red
      font_color: white
      row: 1
    - entity: script.irsend_tv_source
      icon: mdi:login
      label: Source
      row: 1
    - entity: script.irsend_tv_stb_power
      icon: mdi:power
      label: STB
      background_color: red
      font_color: white
      row: 1
    - entity: script.irsend_tv_stb_guide
      label: STB Guide
      column: 2
      row: 2
    - entity: script.irsend_tv_stb_menu
      label: STB Menu
      column: 3
      row: 2
    - entity: script.irsend_tv_key_1
      label: 1
      row: 3
    - entity: script.irsend_tv_key_2
      label: 2
      row: 3
    - entity: script.irsend_tv_key_3
      label: 3
      row: 3
    - entity: script.irsend_tv_key_4
      label: 4
      row: 4
    - entity: script.irsend_tv_key_5
      label: 5
      row: 4
    - entity: script.irsend_tv_key_6
      label: 6
      row: 4
    - entity: script.irsend_tv_key_7
      label: 7
      row: 5
    - entity: script.irsend_tv_key_8
      label: 8
      row: 5
    - entity: script.irsend_tv_key_9
      label: 9
      row: 5
    - entity: script.irsend_tv_key_minus
      label: '-'
      row: 6
    - entity: script.irsend_tv_key_0
      label: '0'
      row: 6
    - entity: script.irsend_tv_pre_ch
      label: Pre-Ch
      row: 6
    - entity: script.irsend_tv_key_volumeup
      label: Vol+
      background_color: '#c8e4ff'
      row: 7
    - entity: script.irsend_tv_key_mute
      icon: mdi:volume-mute
      label: Mute
      row: 7
    - entity: script.irsend_tv_key_channelup
      label: Ch+
      background_color: '#c8e4ff'
      row: 7
    - entity: script.irsend_tv_key_volumedown
      label: Vol-
      background_color: '#c8e4ff'
      row: 8
    - entity: script.irsend_tv_channel_list
      label: Ch List
      row: 8
    - entity: script.irsend_tv_key_channeldown
      label: Ch-
      background_color: '#c8e4ff'
      row: 8
    - entity: script.irsend_tv_key_menu
      label: Menu
      icon: mdi:menu
      row: 9
    - entity: script.irsend_tv_smart_hub
      label: Smart Hub
      image: /local/images/smart-hub.png
      row: 9
