custom_ui_state_card: state-card-tiles
config:
  columns: 3
  column_width: 75px
  row_height: 75px
  gap: 4px
  color: '#DDDDDD'
  font_color: '#000000'
  entities:
    - entity: script.irsend_tv_key_power
      icon: mdi:power
      background_color: red
      font_color: white
      label: TV
    - entity: script.irsend_tv_source
      icon: mdi:login
      label: Source
    - entity: script.irsend_tv_stb_guide
      label: STB Guide
      column: 2
      row: 2
    - entity: script.irsend_tv_stb_menu
      label: STB Menu
      column: 3
      row: 2
