custom_ui_state_card: state-card-tiles
config:
  columns: 3
  column_width: 75px
  row_height: 75px
  gap: 4px
  color: '#DDDDDD'
  font_color: '#000000'
  entities:
    - entity: script.irsend_tv_key_power
      icon: mdi:power
      label: TV
      background_color: red
      font_color: white
      row: 1
    - entity: script.irsend_tv_source
      icon: mdi:login
      label: Source
      row: 1
    - entity: script.irsend_tv_stb_power
      icon: mdi:power
      label: STB
      background_color: red
      font_color: white
      row: 1
    - entity: script.irsend_tv_stb_guide
      label: STB Guide
      column: 2
      row: 2
    - entity: script.irsend_tv_stb_menu
      label: STB Menu
      column: 3
      row: 2
    - entity: script.irsend_tv_key_1
      icon: mdi:numeric-1-box
      row: 3
    - entity: script.irsend_tv_key_2
      icon: mdi:numeric-2-box
      row: 3
    - entity: script.irsend_tv_key_3
      icon: mdi:numeric-3-box
      row: 3
    - entity: script.irsend_tv_key_4
      icon: mdi:numeric-4-box
      row: 4
    - entity: script.irsend_tv_key_5
      icon: mdi:numeric-5-box
      row: 4
    - entity: script.irsend_tv_key_6
      icon: mdi:numeric-6-box
      row: 4
    - entity: script.irsend_tv_key_7
      icon: mdi:numeric-7-box
      row: 5
    - entity: script.irsend_tv_key_8
      icon: mdi:numeric-8-box
      row: 5
    - entity: script.irsend_tv_key_9
      icon: mdi:numeric-9-box
      row: 5
    - entity: script.irsend_tv_key_minus
      icon: mdi:minus
      row: 6
    - entity: script.irsend_tv_key_0
      icon: mdi:numeric-0-box
      row: 6
    - entity: script.irsend_tv_pre_ch
      label: Pre-Ch
      row: 6
    - entity: script.irsend_tv_key_volumeup
      label: Vol
      icon: mdi:plus
      background_color: '#c8e4ff'
      row: 7
    - entity: script.irsend_tv_key_mute
      icon: mdi:volume-mute
      label: Mute
      row: 7
    - entity: script.irsend_tv_key_channelup
      label: Ch
      icon: mdi:chevron-up
      background_color: '#c8e4ff'
      row: 7
    - entity: script.irsend_tv_key_volumedown
      label: Vol
      icon: mdi:minus
      background_color: '#c8e4ff'
      row: 8
    - entity: script.irsend_tv_channel_list
      label: Ch List
      row: 8
    - entity: script.irsend_tv_key_channeldown
      label: Ch
      icon: mdi:chevron-down
      background_color: '#c8e4ff'
      row: 8
    - entity: script.irsend_tv_key_menu
      label: Menu
      icon: mdi:menu
      row: 9
    - entity: script.irsend_tv_smart_hub
      image: /local/images/smarthub.png
      row: 9
    - entity: script.irsend_tv_guide
      label: Guide
      row: 9
    - entity: script.irsend_tv_tools
      label: Tools
      icon: mdi:open-in-new
      row: 10
    - entity: script.irsend_tv_up
      icon: mdi:arrow-up-bold
      row: 10
    - entity: script.irsend_tv_info
      label: Info
      icon: mdi:information-variant
      row: 10
    - entity: script.irsend_tv_left
      icon: mdi:arrow-left-bold
      row: 11
    - entity: script.irsend_tv_enter
      icon: mdi:image-filter-center-focus
      row: 11
    - entity: script.irsend_tv_right
      icon: mdi:arrow-right-bold
      row: 11
    - entity: script.irsend_tv_return
      icon: mdi:keyboard-return
      row: 12
    - entity: script.irsend_tv_down
      icon: mdi:arrow-down-bold
      row: 12
    - entity: script.irsend_tv_exit
      icon: mdi:exit-to-app
      row: 12
