custom_ui_state_card: state-card-tiles
config:
  columns: 3
  column_width: 100px
  row_height: 55px
  gap: 4px
  color: '#DDDDDD'
  font_color: '#000000'
  entities:
    - entity: script.irsend_tv_key_help
      label: E-Manual
      row: 1
    - entity: script.irsend_tv_key_search
      label: Search
      row: 1
    - entity: script.irsend_tv_key_keyboard
      label: Keyboard
      row: 1
    - entity: script.irsend_tv_psize
      label: P.Size
      row: 2
    - entity: script.irsend_tv_mts
      label: MTS
      row: 2
    - entity: script.irsend_tv_cc
      label: CC
      row: 2
    - entity: script.irsend_tv_rewind
      icon: mdi:rewind
      row: 3
    - entity: script.irsend_tv_pause
      icon: mdi:pause
      row: 3
    - entity: script.irsend_tv_forward
      icon: mdi:fast-forward
      row: 3
    - entity: script.irsend_tv_record
      icon: mdi:record-rec
      row: 4
      font_color: red
    - entity: script.irsend_tv_play
      icon: mdi:play
      row: 4
    - entity: script.irsend_tv_stop
      icon: mdi:stop
      row: 4