custom_ui_state_card: state-card-tiles
config:
  columns: 3
  column_width: 100px
  row_height: 55px
  gap: 4px
  color: '#DDDDDD'
  font_color: '#000000'
  entities:
    - entity: script.irsend_vaccuum_key_power
      icon: mdi:power
      label: Power
      row: 1
      column: 1
    - entity: script.irsend_vaccuum_key_play
      icon: mdi:play-pause
      row: 1
      column: 3
    - entity: script.irsend_vaccuum_key_up
      icon: mdi:arrow-up-bold
      row: 2
      column: 2
    - entity: script.irsend_vaccuum_key_left
      icon: mdi:arrow-left-bold
      row: 3
      column: 1
    - entity: script.irsend_vaccuum_key_enter
      icon: mdi:image-filter-center-focus
      row: 3
      column: 2
    - entity: script.irsend_vaccuum_key_right
      icon: mdi:arrow-right-bold
      row: 3
      column: 3
    - entity: script.irsend_vaccuum_key_down
      icon: mdi:arrow-down-bold
      row: 4
      column: 2
    - entity: script.irsend_vaccuum_key_a
      label: Mode
      icon: mdi:format-rotate-90
      row: 5
      column: 2
    - entity: script.irsend_vaccuum_key_b
      label: Clock
      icon: mdi:clock
      row: 6
      column: 1
    - entity: script.irsend_vaccuum_key_c
      label: Timer
      icon: mdi:camera-timer
      row: 6
      column: 3
    - entity: script.irsend_vaccuum_key_d
      label: Base
      icon: mdi:home
      row: 7
      column: 1
    - entity: script.irsend_vaccuum_key_e
      label: Climb
      icon: mdi:page-layout-footer
      row: 7
      column: 3
    - entity: script.irsend_vaccuum_key_f
      label: Spot
      icon: mdi:refresh
      row: 8
      column: 1
    - entity: script.irsend_vaccuum_key_g
      label: Max
      icon: mdi:flash-circle
      row: 8
      column: 3