living_room_tv:
  command_on: 'bash -c "ping -c 1 192.168.1.137 || irsend SEND_ONCE Living_TV KEY_POWER"'
  command_off: 'bash -c "ping -c 1 192.168.1.137 && irsend SEND_ONCE Living_TV KEY_POWER"'
  command_state: 'ping -c 1 192.168.1.137 | grep "1 received" | wc -l'
  value_template: >
    {{ value == '1' }}
  friendly_name: Living Room TV
