living_room_tv:
  command_on: 'if [ $(ping -c 1 192.168.1.137 | grep "1 received" | wc -l) != "1" ]; then irsend SEND_ONCE Living_TV KEY_POWER; fi'
  command_off: 'if [ $(ping -c 1 192.168.1.137 | grep "1 received" | wc -l) == "1" ]; then irsend SEND_ONCE Living_TV KEY_POWER; fi'
  command_state: 'ping -c 1 192.168.1.137 | grep "1 received" | wc -l'
  value_template: >
    {{ value == '1' }}
  friendly_name: Living Room TV
