#plexmediaserver:
#  command_on: sudo systemctl start plexmediaserver.service
#  command_off: sudo systemctl stop plexmediaserver.service
#  command_state: systemctl is-active plexmediaserver.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: Plex Media Server
#headphones:
#  command_on: sudo systemctl start headphones.service
#  command_off: sudo systemctl stop headphones.service
#  command_state: systemctl is-active headphones.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: Headphones
#sonarr:
#  command_on: sudo systemctl start sonarr@plex.service
#  command_off: sudo systemctl stop sonarr@plex.service
#  command_state: systemctl is-active sonarr@plex.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: Sonarr
#couch_potato:
#  command_on: sudo systemctl start couchpotato.service
#  command_off: sudo systemctl stop couchpotato.service
#  command_state: systemctl is-active couchpotato.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: Couch Potato
#deluge_daemon:
#  command_on: sudo systemctl start deluged@plex.service
#  command_off: sudo systemctl stop deluged@plex.service
#  command_state: systemctl is-active deluged@plex.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: Deluge Daemon
#deluge_web:
#  command_on: sudo systemctl start deluge-web@deluge.service
#  command_off: sudo systemctl stop deluge-web@deluge.service
#  command_state: systemctl is-active deluge-web@deluge.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: Deluge Web
#jackett:
#  command_on: sudo systemctl start jackett@plex.service
#  # Jackett sometimes gets locked up, so we are a little forceful with stopping it.
#  command_off: 'sudo systemctl stop jackett && sleep 5 && pkill -f JackettConsole.exe'
#  command_state: systemctl is-active jackett@plex.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: Jackett
#htpc_manager:
#  command_on: sudo systemctl start htpcmanager@plex.service
#  command_off: sudo systemctl stop htpcmanager@plex.service
#  command_state: systemctl is-active htpcmanager@plex.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: HTPC Manager
#plexpy:
#  command_on: sudo systemctl start plexpy@plex.service
#  command_off: sudo systemctl stop plexpy@plex.service
#  command_state: systemctl is-active plexpy@plex.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: Plexpy
#radarr:
#  command_on: sudo systemctl start radarr@plex.service
#  command_off: sudo systemctl stop radarr@plex.service
#  command_state: systemctl is-active radarr@plex.service >/dev/null 2>&1 && echo active || echo inactive
#  value_template: >
#    {{ value == 'active' }}
#  friendly_name: Radarr
