#sensor.forecastio_daily_high_temperature:
#  friendly_name: High
#sensor.forecastio_daily_low_temperature:
#  friendly_name: Low
#sensor.forecastio_humidity:
#  friendly_name: Humidity
#sensor.forecastio_ozone:
#  friendly_name: Ozone
#sensor.forecastio_temperature:
#  friendly_name: Temperature
#sensor.forecastio_wind_speed:
#  friendly_name: Wind Speed
sensor.los_angeles:
  friendly_name: Torrance
sensor.tokyo:
  friendly_name: Yokohama
automation.automation_0:
  hidden: true
automation.automation_1:
  hidden: true
automation.automation_2:
  hidden: true
automation.automation_3:
  hidden: true
automation.automation_4:
  hidden: true
automation.automation_5:
  hidden: true
automation.automation_6:
  hidden: true
light.livingroomlights_level:
  friendly_name: "Living Room Lights"
switch.frontporchlight_switch:
  friendly_name: "Front Porch Light"
media_player.rasplex:
  friendly_name: "Plex (Blue Room)"
media_player.tv_un55h6300:
  friendly_name: "Living Room TV"
device_tracker.plex_na:
  friendly_name: "Nicholas"
group.tools:
  order: 13
input_boolean.home_phone_nicholas:
  persistent: true
input_boolean.home_phone_tomoko:
  persistent: true
input_boolean.mobile_phone_nicholas:
  persistent: true
input_boolean.mobile_phone_tomoko:
  persistent: true
input_boolean.work_phone_nicholas:
  persistent: true
input_boolean.girls_bedtime_living_lights:
  persistent: true
input_select.theater_style:
  persistent: true
input_select.theater_mode:
  persistent: true
zone.daycare:
  friendly_name: !secret daycare_name
zone.elementary_school:
  friendly_name: !secret elementary_school_name
zone.home:
  friendly_name: Home
zone.home2:
  friendly_name: !secret home2_name
zone.sports_center:
  friendly_name: !secret sports_center_name
zone.preschool:
  friendly_name: !secret preschool_name
zone.work:
  friendly_name: Work
input_text.tv_tiles: !include customize/tv_remote.yaml
input_text.tv_tiles2: !include customize/tv_remote2.yaml
input_text.tv_tiles3: !include customize/tv_remote3.yaml
