#sensor.forecastio_daily_high_temperature:
#  friendly_name: High
#sensor.forecastio_daily_low_temperature:
#  friendly_name: Low
#sensor.forecastio_humidity:
#  friendly_name: Humidity
#sensor.forecastio_ozone:
#  friendly_name: Ozone
#sensor.forecastio_temperature:
#  friendly_name: Temperature
#sensor.forecastio_wind_speed:
#  friendly_name: Wind Speed
sensor.los_angeles:
  friendly_name: Torrance
sensor.tokyo:
  friendly_name: Yokohama
automation.automation_0:
  hidden: true
automation.automation_1:
  hidden: true
automation.automation_2:
  hidden: true
automation.automation_3:
  hidden: true
automation.automation_4:
  hidden: true
automation.automation_5:
  hidden: true
automation.automation_6:
  hidden: true
light.livingroomlights_level:
  friendly_name: "Living Room Lights"
switch.frontporchlight_switch:
  friendly_name: "Front Porch Light"
media_player.rasplex:
  friendly_name: "Plex (Blue Room)"
media_player.tv_un55h6300:
  friendly_name: "Living Room TV"
device_tracker.plex_na:
  friendly_name: "Nicholas"
group.tools:
  order: 13
input_boolean.home_phone_nicholas:
  persistent: true
input_boolean.home_phone_tomoko:
  persistent: true
input_boolean.mobile_phone_nicholas:
  persistent: true
input_boolean.mobile_phone_tomoko:
  persistent: true
input_boolean.work_phone_nicholas:
  persistent: true
input_boolean.girls_bedtime_living_lights:
  persistent: true
input_select.theater_style:
  persistent: true
input_select.theater_mode:
  persistent: true
zone.daycare:
  friendly_name: !secret daycare_name
zone.elementary_school:
  friendly_name: !secret elementary_school_name
zone.home:
  friendly_name: Home
zone.home2:
  friendly_name: !secret home2_name
zone.sports_center:
  friendly_name: !secret sports_center_name
zone.preschool:
  friendly_name: !secret preschool_name
zone.work:
  friendly_name: Work
input_text.tv_tiles: !include customize/tv_remote.yaml
input_text.tv_tiles2: !include customize/tv_remote2.yaml
input_text.tv_tiles3: !include customize/tv_remote3.yaml
input_text.vacuum_tiles: !include customize/vacuum_remote.yaml
zwave.livingroomlights:
  google_assistant_name: not the living room lights
light.livingroomlights_level:
  google_assistant: True
  google_assistant_name: Living Room Lights
switch.living_room_tv:
  google_assistant: True
  google_assistant_name: TV
  aliases:
    - Living Room TV
    - Television
cover.garage_door:
  google_assistant: True
  google_assistant_name: Garage
  aliases:
    - Garage Door
switch.diningoutlet_switch:
  google_assistant: True
  google_assistant_name: Dining Outlet
  aliases:
    - Dining Room Outlet
    - Dining Room Outlet Switch
    - Christmas Tree
scene.bedtime:
  google_assistant: True
  google_assistant_name: Go to bed
  aliases:
    - Go to bed scene
    - Go to sleep
    - Bedtime
    - Bedtime scene
script.irsend_tv_key_mute:
  google_assistant: True
  google_assistant_name: Mute
  aliases:
    - Mute the TV
    - Mute the Living Room TV
    - Unmute
    - Unmute the TV
    - Unmute the Living Room TV
switch.home_phone_nicholas:
  google_assistant: True
  google_assistant_name: Nicholases Home Phone
  aliases:
    - Home phone call forwarding for Nicholas
    - Home phone call forwarding
    - Home call forwarding
    - Nicholases Home Phone call forwarding
    - Nicholases Home Phone
    - Nicholas' Home Phone
    - Home Phone
switch.work_phone_nicholas:
  google_assistant: True
  google_assistant_name: Nicholases Work Phone
  aliases:
    - Work phone call forwarding for Nicholas
    - Work phone call forwarding
    - Work phone forwarding
    - Nicholases Work Phone call forwarding
    - Nicholases Work Phone
    - Nicholas' Work Phone
    - Work Phone