name: 'Home'
latitude: !secret latitude_home
longitude: !secret longitude_home
elevation: !secret elevation
unit_system: imperial
time_zone: !secret time_zone
customize: !include_dir_merge_named customize/
packages: !include_dir_named packages