holiday_lighting:
  name: Holiday Lighting
  initial: off
  icon: mdi:light
christmas_tree:
  name: Christmas Tree
  initial: off
  icon: mdi:pine-tree
home_phone_nicholas:
home_phone_tomoko:
mobile_phone_nicholas:
mobile_phone_tomoko:
work_phone_nicholas:
