theater_mode:
  name: Theater Mode
  initial: Disabled
  options:
   - Disabled
   - After Sunset
   - Always On
  initial: Disabled
theater_style:
  name: Theater Style
  initial: Hybrid
  options:
   - Hybrid
   - Dim Everything
   - Lights Out
