theater_mode:
  name: Theater Mode
  initial: Disabled
  options:
   - Disabled
   - After Sunset
   - Always On
theater_style:
  name: Theater Style
  initial: Hybrid
  options:
   - Hybrid
   - Dim Everything
   - Lights Out
holiday_lighting:
  name: Holiday Lighting
  initial: Off
  options:
   - Off
   - On
