- name: Livingroom normal
  entities:
    light.livingroomlights_level_2:
      state: on
      brightness: 255
- name: Livingroom dim
  entities:
    light.livingroomlights_level_2:
      state: on
      brightness: 75
- name: Livingroom dark
  entities:
    light.livingroomlights_level_2:
      state: off
- name: Theater Mode Disabled
  entities:
    group.theater_automations:
      state: off
- name: Theater Mode Always On
  entities:
    group.theater_automations:
      state: on
- name: Theater Mode After Sunset
  entities:
    group.theater_automations:
      state: on
#- name: Theater Style Hybrid
#- name: Theater Style Dim Everything
#- name: Theater Style Lights Out
