- platform: yr
- platform: plex
  name: Plex
  host: !secret plex_host
  username: !secret plex_username
  password: !secret plex_api_key
  server: !secret plex_servername
- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - icon
    - wind_speed
    - wind_bearing
    - humidity
    - ozone
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
- platform: worldclock
  time_zone: America/Los_Angeles
  name: los_angeles
- platform: worldclock
  time_zone: Asia/Tokyo
  name: tokyo
- platform: template
  sensors:
    now:
      value_template: '{{ as_timestamp(now()) | timestamp_custom("%-I:%M %p") }}'
      friendly_name: 'Local Time'
      entity_id:
        - sensor.los_angeles
- platform: ups
  username: !secret ups_username
  password: !secret ups_password
  name: UPS Delivery
- platform: fedex
  username: !secret fedex_username
  password: !secret fedex_password
  name: Fedex Delivery
#- platform: usps
#  username: !secret usps_username
#  password: !secret usps_password
#  name: USPS Delivery
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /media/drives
    - type: memory_free
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
#- platform: pi_hole
#  host: !secret pi_hole_host
#  ssl: True
- platform: mqtt
  state_topic: plexpy/status
  value_template: >
    {%- if value_json.metadata.media_type == 'movie' -%}
      {{ value_json.session.id }}.{{ value_json.metadata.imdb_id }}
    {%- elif value_json.metadata.media_type == 'episode' -%}
      {{ value_json.session.id }}.{{ value_json.metadata.thetvdb_id }}.{{ value_json.metadata.parent_media_index }}.{{ value_json.metadata.media_index }}
    {%- elif value_json.metadata.media_type == 'track' -%}
      {{ value_json.session.id }}.{{ value_json.metadata.lastfm_id }}
    {%- else -%}
      {{ value_json.session.id }}.{{ value_json.title }}
    {%- endif -%}
  name: Plexpy tag
- platform: mqtt
  state_topic: plexpy/status
  value_template: '{{ value_json.poster_url }}'
  name: Plexpy poster
- platform: mqtt
  state_topic: plexpy/status
  value_template: '{{ value_json.title }}'
  name: Plexpy Title
- platform: mqtt
  state_topic: plexpy/status
  value_template: '{{ value_json.body }}'
  name: Plexpy Body
- platform: mqtt
  state_topic: plexpy/status
  value_template: '{{ value_json }}'
  name: Plexpy data
- platform: mqtt
  state_topic: garage/opened
  name: Garage last opened
- platform: ink
  host: IP_ADDRESS
  scan_interval: 120
  resources:
   - black
   - cyan
   - magenta
   - yellow
   - photoblack
   - photocyan
   - photomagenta
   - photoyellow
   - photogrey