- platform: yr
- platform: plex
  name: Plex
  host: !secret plex_host
  username: !secret plex_username
  password: !secret plex_api_key
  server: !secret plex_servername
- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - icon
    - wind_speed
    - wind_bearing
    - humidity
    - ozone
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
- platform: worldclock
  time_zone: America/Los_Angeles
  name: los_angeles
- platform: worldclock
  time_zone: Asia/Tokyo
  name: tokyo
- platform: template
  sensors:
    now:
      value_template: '{{ as_timestamp(now()) | timestamp_custom("%-I:%M %p") }}'
      friendly_name: 'Local Time'
      entity_id:
        - sensor.los_angeles
    plex_token:
      value_template: !secret plex_token
      friendly_name: 'Plex Token'
#    plex_title:
#      value_template: shell_command.plex_show
- platform: mqtt
  name: Plex Title
  state_topic: "plex/title"
- platform: ups
  username: !secret ups_username
  password: !secret ups_password
  name: UPS Delivery
- platform: fedex
  username: !secret fedex_username
  password: !secret fedex_password
  name: Fedex Delivery
- platform: usps
  username: !secret usps_username
  password: !secret usps_password
  name: USPS Delivery
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /media/drives
    - type: memory_free
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
- platform: pi_hole
- platform: mqtt
  state_topic: plex-watch/start
  value_template: '{{ value_json.body }}'
- platform: mqtt
  state_topic: plex-watch/start
  value_template: '{{ value_json.title }}'
