- platform: command_line
  switches:
    plexmediaserver:
      command_on: sudo systemctl start plexmediaserver
      command_off: sudo systemctl stop plexmediaserver
      command_state: systemctl is-active plexmediaserver
      value_template: >
        {{ value == 'active' }}
      friendly_name: Plex Media Server
    headphones:
      command_on: sudo systemctl start headphones
      command_off: sudo systemctl stop headphones
      command_state: systemctl is-active headphones
      value_template: >
        {{ value == 'active' }}
      friendly_name: Headphones
    sonarr:
      command_on: sudo systemctl start sonarr
      command_off: sudo systemctl stop sonarr
      command_state: systemctl is-active sonarr
      value_template: >
        {{ value == 'active' }}
      friendly_name: Sonarr
    couchpotato:
      command_on: sudo systemctl start couchpotato
      command_off: sudo systemctl stop couchpotato
      command_state: systemctl is-active couchpotato
      value_template: >
        {{ value == 'active' }}
      friendly_name: Couch Potato
    deluged:
      command_on: sudo systemctl start deluged
      command_off: sudo systemctl stop deluged
      command_state: systemctl is-active deluged
      value_template: >
        {{ value == 'active' }}
      friendly_name: Deluge Daemon
    delugeweb:
      command_on: sudo systemctl start deluge-web
      command_off: sudo systemctl stop deluge-web
      command_state: systemctl is-active deluge-web
      value_template: >
        {{ value == 'active' }}
      friendly_name: Deluge Web
    jackett:
      command_on: sudo systemctl start jackett
      command_off: sudo systemctl stop jackett
      command_state: systemctl is-active jackett
      value_template: >
        {{ value == 'active' }}
      friendly_name: Jackett
- platform: template
  switches:
    theatermode:
      friendly_name: "Theater Mode"
      value_template: '{{ is_state("group.theater_automations", "on") }}'
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.theater_automations
      turn_off:
        service: homeassistant.turn_off
        entity_id: group.theater_automations
    front_porch_light:
      friendly_name: 'Front Porch Light'
      value_template: '{{states.switch.frontporchlight_switch_3.state}}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.frontporchlight_switch_3
      turn_off:
        service: switch.turn_off
        entity_id: switch.frontporchlight_switch_3
