home:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 80
  icon: mdi:home
work:
  name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 80
  icon: mdi:domain