usb_path: /dev/ttyUSB-zwave
config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
polling_interval: 60000
new_entity_ids: true
network_key: !secret zwave_network_key
device_config:
  light.livingroomlights_level:
    polling_intensity: 1
  switch.frontporchlight_switch:
    polling_intensity: 1
