default_view:
  view: yes
  entities:
    - group.forecast
    - group.servers
    - group.switches
    - group.theater_mode
    - media_player.rasplex
    - media_player.tv_un55h6300
    - sensor.los_angeles
    - sensor.tokyo
    - device_tracker.plex_na
    - group.phone_switches