tv_script:
  name: TV
  entities:
    - irsend_tv_key_power
    - irsend_tv_source
    - irsend_tv_stb_guide
    - irsend_tv_stb_menu
    - irsend_tv_key_1
    - irsend_tv_key_2
    - irsend_tv_key_3
    - irsend_tv_key_4
    - irsend_tv_key_5
    - irsend_tv_key_6
    - irsend_tv_key_7
    - irsend_tv_key_8
    - irsend_tv_key_9
    - irsend_tv_key_0
    - irsend_tv_key_minus
    - irsend_tv_pre_ch
    - irsend_tv_stb_power
    - irsend_tv_key_volumeup
    - irsend_tv_key_volumedown
    - irsend_tv_key_mute
    - irsend_tv_channel_list
    - irsend_tv_key_channelup
    - irsend_tv_key_channeldown
    - irsend_tv_key_menu
    - irsend_tv_smart_hub
    - irsend_tv_guide
    - irsend_tv_tools
    - irsend_tv_key_info
    - irsend_tv_key_return
    - irsend_tv_key_exit
    - irsend_tv_key_select
    - irsend_tv_key_up
    - irsend_tv_key_down
    - irsend_tv_key_left
    - irsend_tv_key_right
    - irsend_tv_key_a
    - irsend_tv_key_b
    - irsend_tv_key_c
    - irsend_tv_key_d
    - irsend_tv_key_help
    - irsend_tv_key_search
    - irsend_tv_key_keyboard
    - irsend_tv_psize
    - irsend_tv_mts
    - irsend_tv_key_cc
    - irsend_tv_key_rewind
    - irsend_tv_key_pause
    - irsend_tv_key_forward
    - irsend_tv_key_record
    - irsend_tv_key_play
    - irsend_tv_key_stop
