tv_script:
  name: TV
  entities:
    - script.irsend_tv_key_power
    - script.irsend_tv_source
    - script.irsend_tv_stb_guide
    - script.irsend_tv_stb_menu
    - script.irsend_tv_key_1
    - script.irsend_tv_key_2
    - script.irsend_tv_key_3
    - script.irsend_tv_key_4
    - script.irsend_tv_key_5
    - script.irsend_tv_key_6
    - script.irsend_tv_key_7
    - script.irsend_tv_key_8
    - script.irsend_tv_key_9
    - script.irsend_tv_key_0
    - script.irsend_tv_key_minus
    - script.irsend_tv_pre_ch
    - script.irsend_tv_stb_power
    - script.irsend_tv_key_volumeup
    - script.irsend_tv_key_volumedown
    - script.irsend_tv_key_mute
    - script.irsend_tv_channel_list
    - script.irsend_tv_key_channelup
    - script.irsend_tv_key_channeldown
    - script.irsend_tv_key_menu
    - script.irsend_tv_smart_hub
    - script.irsend_tv_guide
    - script.irsend_tv_tools
    - script.irsend_tv_key_info
    - script.irsend_tv_key_return
    - script.irsend_tv_key_exit
    - script.irsend_tv_key_select
    - script.irsend_tv_key_up
    - script.irsend_tv_key_down
    - script.irsend_tv_key_left
    - script.irsend_tv_key_right
    - script.irsend_tv_key_a
    - script.irsend_tv_key_b
    - script.irsend_tv_key_c
    - script.irsend_tv_key_d
    - script.irsend_tv_key_help
    - script.irsend_tv_key_search
    - script.irsend_tv_key_keyboard
    - script.irsend_tv_psize
    - script.irsend_tv_mts
    - script.irsend_tv_key_cc
    - script.irsend_tv_key_rewind
    - script.irsend_tv_key_pause
    - script.irsend_tv_key_forward
    - script.irsend_tv_key_record
    - script.irsend_tv_key_play
    - script.irsend_tv_key_stop
