switches:
  name: Switches
  entities:
    - light.livingroomlights_level
    - switch.frontporchlight_switch
    - switch.diningoutlet_switch
    - switch.outsideoutlet_switch
    - cover.garage_door
    - switch.living_room_tv
    - script.away
    - scene.nicholas_mobile_phone_only
