switches:
  name: Switches
  entities:
    - light.livingroomlights_level
    - switch.frontporchlight_switch
    - switch.diningoutlet_switch
    - switch.outsideoutlet_switch
    - switch.kitchen_eaves_outlet_switch
    - switch.gabled_roof_outlet_switch
    - switch.garage_eaves_outlet_switch
    - switch.front_porch_outlet_switch
    - cover.garage_door
    - switch.living_room_tv
    - script.away
    - scene.nicholas_mobile_phone_only
    - script.google_test