irsend_tv_key_power: 'irsend SEND_ONCE Living_TV KEY_POWER'
irsend_tv_source: 'irsend SEND_ONCE Living_TV SOURCE'
irsend_tv_stb_guide: 'irsend SEND_ONCE Living_TV STB_GUIDE'
irsend_tv_stb_menu: 'irsend SEND_ONCE Living_TV STB_MENU'
irsend_tv_key_1: 'irsend SEND_ONCE Living_TV KEY_1'
irsend_tv_key_2: 'irsend SEND_ONCE Living_TV KEY_2'
irsend_tv_key_3: 'irsend SEND_ONCE Living_TV KEY_3'
irsend_tv_key_4: 'irsend SEND_ONCE Living_TV KEY_4'
irsend_tv_key_5: 'irsend SEND_ONCE Living_TV KEY_5'
irsend_tv_key_6: 'irsend SEND_ONCE Living_TV KEY_6'
irsend_tv_key_7: 'irsend SEND_ONCE Living_TV KEY_7'
irsend_tv_key_8: 'irsend SEND_ONCE Living_TV KEY_8'
irsend_tv_key_9: 'irsend SEND_ONCE Living_TV KEY_9'
irsend_tv_key_0: 'irsend SEND_ONCE Living_TV KEY_0'
irsend_tv_key_minus: 'irsend SEND_ONCE Living_TV KEY_MINUS'
irsend_tv_pre_ch: 'irsend SEND_ONCE Living_TV PRE_CH'
irsend_tv_stb_power: 'irsend SEND_ONCE Living_TV STB_POWER'
irsend_tv_key_volumeup: 'irsend SEND_ONCE Living_TV KEY_VOLUMEUP'
irsend_tv_key_volumedown: 'irsend SEND_ONCE Living_TV KEY_VOLUMEDOWN'
irsend_tv_key_mute: 'irsend SEND_ONCE Living_TV KEY_MUTE'
irsend_tv_channel_list: 'irsend SEND_ONCE Living_TV CHANNEL_LIST'
irsend_tv_key_channelup: 'irsend SEND_ONCE Living_TV KEY_CHANNELUP'
irsend_tv_key_channeldown: 'irsend SEND_ONCE Living_TV KEY_CHANNELDOWN'
irsend_tv_key_menu: 'irsend SEND_ONCE Living_TV KEY_MENU'
irsend_tv_smart_hub: 'irsend SEND_ONCE Living_TV SMART_HUB'
irsend_tv_guide: 'irsend SEND_ONCE Living_TV GUIDE'
irsend_tv_tools: 'irsend SEND_ONCE Living_TV TOOLS'
irsend_tv_key_info: 'irsend SEND_ONCE Living_TV KEY_INFO'
irsend_tv_key_return: 'irsend SEND_ONCE Living_TV KEY_RETURN'
irsend_tv_key_exit: 'irsend SEND_ONCE Living_TV KEY_EXIT'
irsend_tv_key_select: 'irsend SEND_ONCE Living_TV KEY_SELECT'
irsend_tv_key_up: 'irsend SEND_ONCE Living_TV KEY_UP'
irsend_tv_key_down: 'irsend SEND_ONCE Living_TV KEY_DOWN'
irsend_tv_key_left: 'irsend SEND_ONCE Living_TV KEY_LEFT'
irsend_tv_key_right: 'irsend SEND_ONCE Living_TV KEY_RIGHT'
irsend_tv_key_a: 'irsend SEND_ONCE Living_TV KEY_A'
irsend_tv_key_b: 'irsend SEND_ONCE Living_TV KEY_B'
irsend_tv_key_c: 'irsend SEND_ONCE Living_TV KEY_C'
irsend_tv_key_d: 'irsend SEND_ONCE Living_TV KEY_D'
irsend_tv_key_help: 'irsend SEND_ONCE Living_TV KEY_HELP'
irsend_tv_key_search: 'irsend SEND_ONCE Living_TV KEY_SEARCH'
irsend_tv_key_keyboard: 'irsend SEND_ONCE Living_TV KEY_KEYBOARD'
irsend_tv_psize: 'irsend SEND_ONCE Living_TV PSIZE'
irsend_tv_mts: 'irsend SEND_ONCE Living_TV MTS'
irsend_tv_key_cc: 'irsend SEND_ONCE Living_TV KEY_CC'
irsend_tv_key_rewind: 'irsend SEND_ONCE Living_TV KEY_REWIND'
irsend_tv_key_pause: 'irsend SEND_ONCE Living_TV KEY_PAUSE'
irsend_tv_key_forward: 'irsend SEND_ONCE Living_TV KEY_FORWARD'
irsend_tv_key_record: 'irsend SEND_ONCE Living_TV KEY_RECORD'
irsend_tv_key_play: 'irsend SEND_ONCE Living_TV KEY_PLAY'
irsend_tv_key_stop: 'irsend SEND_ONCE Living_TV KEY_STOP'
