irsend_vaccuum_key_power: 'irsend SEND_ONCE Vaccuum KEY_POWER'
irsend_vaccuum_key_play: 'irsend SEND_ONCE Vaccuum KEY_PLAY'
irsend_vaccuum_key_up: 'irsend SEND_ONCE Vaccuum KEY_UP'
irsend_vaccuum_key_down: 'irsend SEND_ONCE Vaccuum KEY_DOWN'
irsend_vaccuum_key_left: 'irsend SEND_ONCE Vaccuum KEY_LEFT'
irsend_vaccuum_key_right: 'irsend SEND_ONCE Vaccuum KEY_RIGHT'
irsend_vaccuum_key_enter: 'irsend SEND_ONCE Vaccuum KEY_ENTER'
irsend_vaccuum_key_a: 'irsend SEND_ONCE Vaccuum KEY_A'
irsend_vaccuum_key_b: 'irsend SEND_ONCE Vaccuum KEY_B'
irsend_vaccuum_key_c: 'irsend SEND_ONCE Vaccuum KEY_C'
irsend_vaccuum_key_d: 'irsend SEND_ONCE Vaccuum KEY_D'
irsend_vaccuum_key_e: 'irsend SEND_ONCE Vaccuum KEY_E'
irsend_vaccuum_key_f: 'irsend SEND_ONCE Vaccuum KEY_F'
irsend_vaccuum_key_g: 'irsend SEND_ONCE Vaccuum KEY_G'
