irsend_tv_tv: "irsend SEND_ONCE Samsung_TV TV"
irsend_tv_1: "irsend SEND_ONCE Samsung_TV 1"
irsend_tv_2: "irsend SEND_ONCE Samsung_TV 2"
irsend_tv_3: "irsend SEND_ONCE Samsung_TV 3"
irsend_tv_4: "irsend SEND_ONCE Samsung_TV 4"
irsend_tv_5: "irsend SEND_ONCE Samsung_TV 5"
irsend_tv_6: "irsend SEND_ONCE Samsung_TV 6"
irsend_tv_7: "irsend SEND_ONCE Samsung_TV 7"
irsend_tv_8: "irsend SEND_ONCE Samsung_TV 8"
irsend_tv_9: "irsend SEND_ONCE Samsung_TV 9"
irsend_tv_0: "irsend SEND_ONCE Samsung_TV 0"
irsend_tv_fav_ch: "irsend SEND_ONCE Samsung_TV Fav.Ch"
irsend_tv_pre_ch: "irsend SEND_ONCE Samsung_TV Pre-Ch"
irsend_tv_volu: "irsend SEND_ONCE Samsung_TV VOL+"
irsend_tv_vold: "irsend SEND_ONCE Samsung_TV VOL-"
irsend_tv_mute: "irsend SEND_ONCE Samsung_TV MUTE"
irsend_tv_source: "irsend SEND_ONCE Samsung_TV Source"
irsend_tv_pu: "irsend SEND_ONCE Samsung_TV P+"
irsend_tv_pd: "irsend SEND_ONCE Samsung_TV P-"
irsend_tv_info: "irsend SEND_ONCE Samsung_TV Info"
irsend_tv_menu: "irsend SEND_ONCE Samsung_TV Menu"
irsend_tv_guide: "irsend SEND_ONCE Samsung_TV Guide"
irsend_tv_tools: "irsend SEND_ONCE Samsung_TV Tools"
irsend_tv_return: "irsend SEND_ONCE Samsung_TV Return"
irsend_tv_ch_list: "irsend SEND_ONCE Samsung_TV Ch.List"
irsend_tv_exit: "irsend SEND_ONCE Samsung_TV Exit"
irsend_tv_up: "irsend SEND_ONCE Samsung_TV Up"
irsend_tv_left: "irsend SEND_ONCE Samsung_TV Left"
irsend_tv_right: "irsend SEND_ONCE Samsung_TV Right"
irsend_tv_down: "irsend SEND_ONCE Samsung_TV Down"
irsend_tv_enter: "irsend SEND_ONCE Samsung_TV Enter"
irsend_tv_red: "irsend SEND_ONCE Samsung_TV Red"
irsend_tv_green: "irsend SEND_ONCE Samsung_TV Green"
irsend_tv_yellow: "irsend SEND_ONCE Samsung_TV Yellow"
irsend_tv_blue: "irsend SEND_ONCE Samsung_TV Blue"
irsend_tv_ttx_mix: "irsend SEND_ONCE Samsung_TV TTX/Mix"
irsend_tv_srs: "irsend SEND_ONCE Samsung_TV SRS"
irsend_tv_p_size: "irsend SEND_ONCE Samsung_TV P.Size"
irsend_tv_dual: "irsend SEND_ONCE Samsung_TV Dual"
irsend_tv_ad: "irsend SEND_ONCE Samsung_TV AD"
irsend_tv_subt: "irsend SEND_ONCE Samsung_TV Subt."
irsend_tv_rewind: "irsend SEND_ONCE Samsung_TV Rewind"
irsend_tv_pause: "irsend SEND_ONCE Samsung_TV Pause"
irsend_tv_forward: "irsend SEND_ONCE Samsung_TV Forward"
irsend_tv_record: "irsend SEND_ONCE Samsung_TV Record"
irsend_tv_play: "irsend SEND_ONCE Samsung_TV Play"
irsend_tv_stop: "irsend SEND_ONCE Samsung_TV Stop"
