#plex_show: 'curl -s http://localhost:32400/library/metadata/{{ states.media_player.tv_un55h6300.attributes.media_content_id }}?X-Plex-Token=Lmpm6yYp83wvpP4z2m5q | xmlstarlet sel -t -v "//Video/@grandparentTitle"'
plex_title: 'echo $(curl -s http://localhost:32400/library/metadata/{{ states.media_player.rasplex.attributes.media_content_id }}?X-Plex-Token=Lmpm6yYp83wvpP4z2m5q | xmlstarlet sel -t -v "//Video/@grandparentTitle") > /tmp/media_player.rasplex.title.txt'
reboot_server: 'sudo shutdown -r now'
hass_git_pull: 'cd /home/plex/.homeassistant/ && git pull'
phone_nicholas_home_enable: '/home/plex/.homeassistant/gv-phone.py enable nicholas_home'
phone_nicholas_mobile_enable: '/home/plex/.homeassistant/gv-phone.py enable nicholas_mobile'
phone_nicholas_work_enable: '/home/plex/.homeassistant/gv-phone.py enable nicholas_work'
phone_nicholas_home_disable: '/home/plex/.homeassistant/gv-phone.py disable nicholas_home'
phone_nicholas_mobile_disable: '/home/plex/.homeassistant/gv-phone.py disable nicholas_mobile'
phone_nicholas_work_disable: '/home/plex/.homeassistant/gv-phone.py disable nicholas_work'
phone_tomoko_home_enable: 'sudo su - tomoko -c "/home/plex/.homeassistant/gv-phone.py enable tomoko_home"'
phone_tomoko_mobile_enable: 'sudo su - tomoko -c "/home/plex/.homeassistant/gv-phone.py enable tomoko_mobile"'
phone_tomoko_home_disable: 'sudo su - tomoko -c "/home/plex/.homeassistant/gv-phone.py disable tomoko_home"'
phone_tomoko_mobile_disable: 'sudo su - tomoko -c "/home/plex/.homeassistant/gv-phone.py disable tomoko_mobile"'
