home_phone_nicholas:
  turn_on:
    - service: shell_command.phone_nicholas_home_enable
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_phone_nicholas
  turn_off:
    - service: shell_command.phone_nicholas_home_disable
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_phone_nicholas
  value_template: >
    {{ is_state('input_boolean.home_phone_nicholas', 'on') }}
  friendly_name: Home Phone (Nicholas)
work_phone_nicholas:
  turn_on:
    - service: shell_command.phone_nicholas_work_enable
    - service: input_boolean.turn_off
      entity_id: input_boolean.work_phone_nicholas
  turn_off:
    - service: shell_command.phone_nicholas_work_disable
    - service: input_boolean.turn_off
      entity_id: input_boolean.work_phone_nicholas
  value_template: >
    {{ is_state('input_boolean.work_phone_nicholas', 'on') }}
  friendly_name: Work Phone (Nicholas)
mobile_phone_nicholas:
  turn_on:
    - service: shell_command.phone_nicholas_mobile_enable
    - service: input_boolean.turn_off
      entity_id: input_boolean.mobile_phone_nicholas
  turn_off:
    - service: shell_command.phone_nicholas_mobile_disable
    - service: input_boolean.turn_off
      entity_id: input_boolean.mobile_phone_nicholas
  value_template: >
    {{ is_state('input_boolean.mobile_phone_nicholas', 'on') }}
  friendly_name: Mobile Phone (Nicholas)
home_phone_tomoko:
  turn_on:
    - service: shell_command.phone_tomoko_home_enable
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_phone_tomoko
  turn_off:
    - service: shell_command.phone_tomoko_home_disable
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_phone_tomoko
  value_template: >
    {{ is_state('input_boolean.home_phone_tomoko', 'on') }}
  friendly_name: Home Phone (Tomoko)
mobile_phone_tomoko:
  turn_on:
    - service: shell_command.phone_tomoko_mobile_enable
    - service: input_boolean.turn_off
      entity_id: input_boolean.mobile_phone_tomoko
  turn_off:
    - service: shell_command.phone_tomoko_mobile_disable
    - service: input_boolean.turn_off
      entity_id: input_boolean.mobile_phone_tomoko
  value_template: >
    {{ is_state('input_boolean.work_phone_tomoko', 'on') }}
  friendly_name: Mobile Phone (Tomoko)
