theatermode:
  friendly_name: "Theater Mode"
  value_template: '{{ is_state("group.theater_automations", "on") }}'
  turn_on:
    service: homeassistant.turn_on
    entity_id: group.theater_automations
  turn_off:
    service: homeassistant.turn_off
    entity_id: group.theater_automations